apiVersion: v1
kind: Secret

metadata:
  name: django-secret
  namespace: devsu-demo

type: Opaque

stringData:
  DJANGO_SECRET_KEY: "super-secret-key"
  DATABASE_NAME: "db.sqlite3"
  DATABASE_USER: "postgres"
  DATABASE_PASSWORD: "postgres"
  DATABASE_HOST: "localhost"
  DATABASE_PORT: "5432"